build:created service.html and contacts.html
Simplon-hdf/brief-barber-grp-legendary-cameleon pull request #6
Opened 2024-04-24 13:37 UTC by Achap05

2024-04-24 13:46 UTC, Fethi62000 approved these changes

2024-04-24 13:46 UTC, Fethi62000 approved these changes

2024-04-24 13:50 UTC, RenaudBaussart approved these changes

2024-04-24 14:25 UTC, MikkoPet commented
La nomenclature de la PR, manque le tag :(

2024-04-24 14:27 UTC, RenaudBaussart requested changes
wrong commit naming

2024-04-24 14:40 UTC, MikkoPet approved these changes

2024-04-25 08:05 UTC, RenaudBaussart approved these changes

2024-04-25 08:31 UTC, closed without merging